# Generated by Django 5.1.7 on 2025-04-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
    ]
