# Generated by Django 5.1.7 on 2025-04-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0002_auto_20250412_1308'),
    ]

    operations = [
    ]
