# Generated by Django 5.1.7 on 2025-04-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0003_loanapplication_applicantid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='applicantID',
            new_name='loanID',
        ),
    ]
