# Generated by Django 5.1.6 on 2025-03-11 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account_holder_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account_number',
            field=models.CharField(default='0000000000', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='Account number must be between 9 to 18 digits.', regex='^\\d{9,18}$')]),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'Savings'), (2, 'Current')], default=1),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_branch',
            field=models.CharField(default='Unknown Branch', max_length=255),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_name',
            field=models.CharField(default='Unknown Bank', max_length=255),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='ifsc_code',
            field=models.CharField(default='00000000000', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid IFSC Code format.', regex='^[A-Z]{4}[0-9]{7}$')]),
        ),
    ]
