# Generated by Django 5.1.7 on 2025-04-04 07:37

import django.core.validators
import django.db.models.deletion
import finance_app.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(default=finance_app.models.generate_userID, editable=False, max_length=10, unique=True)),
                ('title', models.IntegerField(choices=[(1, 'Mr.'), (2, 'Mrs.'), (3, 'Ms.'), (4, 'Dr.')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('marital_status', models.IntegerField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_branch', models.CharField(max_length=100)),
                ('account_type', models.IntegerField(choices=[(1, 'Savings'), (2, 'Current'), (3, 'Salary'), (4, 'Fixed Deposit')])),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking_details', to='finance_app.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed'), ('freelancer', 'Freelancer'), ('unemployed', 'Unemployed')], max_length=20)),
                ('job_title', models.CharField(max_length=100)),
                ('years_with_employer', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_details', to='finance_app.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('land', 'Land'), ('house', 'House'), ('apartment', 'Apartment'), ('commercial', 'Commercial Property')], max_length=20)),
                ('property_address', models.TextField()),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('property_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('property_ownership', models.IntegerField(choices=[(1, 'Owned'), (2, 'Mortgaged')])),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='finance_app.applicant')),
            ],
        ),
    ]
