# Generated by Django 5.1.7 on 2025-03-29 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loan_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='tenure',
            new_name='duration_months',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='position',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='status',
        ),
        migrations.AlterField(
            model_name='employment',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
