# Generated by Django 5.1.6 on 2025-03-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='loan_count',
            field=models.IntegerField(default=0),
        ),
    ]
