# Generated by Django 5.1.7 on 2025-03-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_applicant_loan_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='loan_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
