# Generated by Django 5.1.7 on 2025-04-04 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_applicant_loan_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_branch', models.CharField(max_length=100)),
                ('account_type', models.IntegerField(choices=[(1, 'Savings Account'), (2, 'Current Account'), (3, 'Salary Account'), (4, 'Fixed Deposit Account')])),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_details', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Banking Detail',
                'verbose_name_plural': 'Banking Details',
            },
        ),
    ]
