# Generated by Django 5.1.7 on 2025-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_alter_applicant_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='loan_id',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
    ]
