# Generated by Django 5.1.7 on 2025-04-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_remove_applicant_loan_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='marital_status',
            new_name='maritalStatus',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='postal_code',
            new_name='postalCode',
        ),
        migrations.RenameField(
            model_name='bankingdetails',
            old_name='account_holder_name',
            new_name='accountHolderName',
        ),
        migrations.RenameField(
            model_name='bankingdetails',
            old_name='account_number',
            new_name='accountNumber',
        ),
        migrations.RenameField(
            model_name='bankingdetails',
            old_name='account_type',
            new_name='accountType',
        ),
        migrations.RenameField(
            model_name='bankingdetails',
            old_name='bank_branch',
            new_name='bankBranch',
        ),
        migrations.RenameField(
            model_name='bankingdetails',
            old_name='bank_name',
            new_name='bankName',
        ),
        migrations.RenameField(
            model_name='bankingdetails',
            old_name='ifsc_code',
            new_name='ifscCode',
        ),
        migrations.RenameField(
            model_name='employmentdetails',
            old_name='employment_type',
            new_name='employmentType',
        ),
        migrations.RenameField(
            model_name='employmentdetails',
            old_name='job_title',
            new_name='jobTitle',
        ),
        migrations.RenameField(
            model_name='employmentdetails',
            old_name='monthly_income',
            new_name='monthlyIncome',
        ),
        migrations.RenameField(
            model_name='employmentdetails',
            old_name='other_income',
            new_name='otherIncome',
        ),
        migrations.RenameField(
            model_name='employmentdetails',
            old_name='years_with_employer',
            new_name='yearsWithEmployer',
        ),
        migrations.RenameField(
            model_name='propertydetails',
            old_name='property_age',
            new_name='propertyAge',
        ),
        migrations.RenameField(
            model_name='propertydetails',
            old_name='property_ownership',
            new_name='propertyOwnership',
        ),
        migrations.RenameField(
            model_name='propertydetails',
            old_name='property_type',
            new_name='propertyType',
        ),
        migrations.RenameField(
            model_name='propertydetails',
            old_name='property_value',
            new_name='propertyValue',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='agree_credit_check',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='agree_data_sharing',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='agree_terms',
        ),
    ]
