# Generated by Django 5.1.7 on 2025-04-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_rename_date_of_birth_applicant_dateofbirth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantproof',
            old_name='proof_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='applicantproof',
            old_name='proof_number',
            new_name='idNumber',
        ),
        migrations.RenameField(
            model_name='applicantproof',
            old_name='proof_type',
            new_name='type',
        ),
    ]
