# Generated by Django 5.1.7 on 2025-04-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0013_remove_applicant_dateofbirth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='marital_status',
            new_name='maritalStatus',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='postal_code',
            new_name='postalCode',
        ),
    ]
