# Generated by Django 5.1.6 on 2025-03-11 06:45

import applicants.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(default=applicants.models.generate_userID, editable=False, max_length=10, unique=True)),
                ('loan_id', models.IntegerField(editable=False, null=True, unique=True)),
                ('loanreg_date', models.DateField(auto_now_add=True)),
                ('title', models.IntegerField(blank=True, choices=[(1, 'Mr.'), (2, 'Mrs.'), (3, 'Ms.'), (4, 'Dr.')], null=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('marital_status', models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed')], null=True)),
                ('email', models.EmailField(max_length=35, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('applicant_photo', models.ImageField(blank=True, null=True, upload_to='uploads/images/customer/')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.IntegerField(choices=[(1, 'PAN Card'), (2, 'Aadhar Card'), (3, 'Voter ID')])),
                ('proof_number', models.CharField(max_length=50, unique=True)),
                ('proof_file', models.FileField(upload_to='uploads/files/customerproof/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='applicants.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('years_with_employer', models.IntegerField(blank=True, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='applicants.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('property_age', models.IntegerField(blank=True, null=True)),
                ('property_ownership', models.IntegerField(choices=[(1, 'Owned'), (2, 'Mortgaged')], default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('agree_terms', models.BooleanField(default=False)),
                ('agree_credit_check', models.BooleanField(default=False)),
                ('agree_data_sharing', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='applicants.applicant')),
            ],
        ),
    ]
