# Generated by Django 5.1.7 on 2025-04-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_bankingdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='loan_count',
        ),
    ]
