# Generated by Django 5.1.7 on 2025-04-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_rename_proof_file_applicantproof_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantproof',
            name='type',
            field=models.IntegerField(choices=[(1, 'pan'), (2, 'aadhar'), (3, 'voterId'), (4, 'Driving License')]),
        ),
    ]
