# Generated by Django 5.1.7 on 2025-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_alter_applicantproof_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantproof',
            name='type',
            field=models.CharField(choices=[('pan', 'pan'), ('aadhar', 'aadhar'), ('voterId', 'voterId'), ('Driving License', 'Driving License')]),
        ),
    ]
