# Generated by Django 5.1.7 on 2025-04-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0010_alter_applicantproof_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='applicant_photo',
            new_name='profile_photo',
        ),
    ]
