# Generated by Django 5.1.7 on 2025-04-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0011_rename_applicant_photo_applicant_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentdetails',
            name='employmentType',
            field=models.IntegerField(blank=True, choices=[(1, 'Agricultural Laborers'), (2, 'Private Jobs'), (3, 'Daily Wage Laborers'), (4, 'Cottage Industry Workers'), (5, 'Dairy Workers'), (6, 'Rural Shopkeepers'), (7, 'Government'), (8, 'Transport Operators')], null=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='propertyType',
            field=models.IntegerField(blank=True, choices=[(1, 'Agricultural Land'), (2, 'Kutcha House (Mud/Clay)'), (3, 'Pucca House (Cement/Brick)'), (4, 'Farm House'), (5, 'Cattle Shed'), (6, 'Storage Shed/Granary'), (7, 'Residential Plot'), (8, 'Village Shop'), (9, 'Joint Family House'), (10, 'Vacant Land within Village')], null=True),
        ),
    ]
