# Generated by Django 5.1.7 on 2025-04-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0012_alter_employmentdetails_employmenttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='maritalStatus',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='postalCode',
        ),
        migrations.AddField(
            model_name='applicant',
            name='date_of_birth',
            field=models.DateField(blank=True, db_column='dateOfBirth', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed')], db_column='maritalStatus', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='postal_code',
            field=models.CharField(blank=True, db_column='postalCode', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='profile_photo',
            field=models.ImageField(blank=True, db_column='applicant_photo', null=True, upload_to='uploads/images/customer/'),
        ),
    ]
