# Generated by Django 5.1.7 on 2025-04-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0014_rename_date_of_birth_applicant_dateofbirth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='maritalStatus',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed')], null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='postalCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/customer/'),
        ),
    ]
