# Generated by Django 5.1.7 on 2025-04-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0015_remove_applicant_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
