# Generated by Django 5.1.7 on 2025-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0016_applicant_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantproof',
            name='idNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
