# Generated by Django 5.1.7 on 2025-05-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0017_alter_applicantproof_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantproof',
            name='idNumber',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
