# Generated by Django 5.1.7 on 2025-05-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0018_alter_applicantproof_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='loan_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='applicantproof',
            name='type',
            field=models.CharField(choices=[('pan', 'PAN Card'), ('aadhar', 'Aadhar Card'), ('voterId', 'Voter ID'), ('Driving License', 'Driving License')], max_length=50),
        ),
    ]
