# Generated by Django 5.1.7 on 2025-05-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0019_alter_applicant_loan_id_alter_applicantproof_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/customer/', verbose_name='Profile Photo'),
        ),
    ]
