# Generated by Django 5.1.7 on 2025-05-07 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0019_alter_applicantproof_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantproof',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ApplicantProof', to='applicants.applicant'),
        ),
    ]
