# Generated by Django 5.1.7 on 2025-05-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0020_alter_applicant_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantproof',
            name='type',
            field=models.CharField(choices=[('pan', 'pan'), ('aadhar', 'aadhar'), ('voterId', 'voterId'), ('drivingLicense', 'drivingLicense')], max_length=50),
        ),
    ]
