# Generated by Django 5.1.7 on 2025-05-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0020_alter_applicantproof_applicant'),
        ('applicants', '0021_alter_applicantproof_type'),
    ]

    operations = [
    ]
