# Generated by Django 5.1.7 on 2025-05-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0022_merge_20250508_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='loan_id',
        ),
    ]
