# Generated by Django 5.1.7 on 2025-04-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('term', models.IntegerField()),
                ('termType', models.CharField(max_length=10)),
                ('interestRate', models.FloatField()),
                ('purpose', models.CharField(max_length=100)),
                ('repaymentSource', models.CharField(max_length=100)),
                ('agreeTerms', models.BooleanField(default=False)),
                ('agreeCreditCheck', models.BooleanField(default=False)),
                ('agreeDataSharing', models.BooleanField(default=False)),
                ('translatorName', models.CharField(max_length=100)),
                ('translatorPlace', models.CharField(max_length=100)),
                ('LoanRegDate', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('startDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EMISchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('emiStartDate', models.DateField()),
                ('emiTotalMonth', models.IntegerField()),
                ('interest', models.FloatField()),
                ('principalPaid', models.FloatField()),
                ('remainingBalance', models.FloatField()),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emiSchedule', to='loanapp.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('relationship', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('idProofType', models.CharField(max_length=100)),
                ('idProofNumber', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(upload_to='nominee_photos/')),
                ('id_proof_file', models.FileField(upload_to='nominee_id_proofs/')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='loanapp.loanapplication')),
            ],
        ),
    ]
