# Generated by Django 5.1.7 on 2025-04-12 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term', models.PositiveIntegerField()),
                ('termType', models.CharField(choices=[('1', 'Days'), ('2', 'Weeks'), ('3', 'Months'), ('4', 'Years')], max_length=1)),
                ('interestRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purpose', models.CharField(choices=[('1', 'Personal'), ('2', 'Business'), ('3', 'Education'), ('4', 'Medical'), ('5', 'Home Improvement')], max_length=1)),
                ('repaymentSource', models.CharField(max_length=100)),
                ('agreeTerms', models.BooleanField(default=False)),
                ('agreeCreditCheck', models.BooleanField(default=False)),
                ('agreeDataSharing', models.BooleanField(default=False)),
                ('translatorName', models.CharField(blank=True, max_length=100, null=True)),
                ('translatorPlace', models.CharField(blank=True, max_length=100, null=True)),
                ('LoanRegDate', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('startDate', models.DateField()),
                ('applicant_photo', models.ImageField(blank=True, null=True, upload_to='applicant_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EMISchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('emiStartDate', models.DateField()),
                ('emiTotalMonth', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principalPaid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remainingBalance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emiSchedule', to='loanapp.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('relationship', models.CharField(choices=[('1', 'Spouse'), ('2', 'Parent'), ('3', 'Sibling'), ('4', 'Friend'), ('5', 'Other')], max_length=1)),
                ('address', models.TextField()),
                ('idProofType', models.CharField(max_length=50)),
                ('idProofNumber', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='nominee_photos/')),
                ('id_proof_file', models.FileField(blank=True, null=True, upload_to='nominee_id_proofs/')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='loanapp.loanapplication')),
            ],
        ),
    ]
