# Generated by Django 5.1.7 on 2025-05-20 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0022_merge_20250508_1556'),
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='applicant_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='applicants.applicant', to_field='userID'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('INFO_REQUESTED', 'Information Requested'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active / Ongoing'), ('PAID', 'Paid / Closed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by Applicant'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='LoanRegDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
