# Generated by Django 5.1.7 on 2025-04-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emischedule',
            name='paymentAmount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emischedule',
            name='pendingAmount',
            field=models.FloatField(default=0.0),
        ),
    ]
