# Generated by Django 5.1.7 on 2025-04-21 06:36

import loanapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0002_emischedule_paymentamount_emischedule_pendingamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='applicantID',
            field=models.CharField(default=loanapp.models.generate_userID, editable=False, max_length=10, unique=True),
        ),
    ]
