# Generated by Django 5.1.7 on 2025-05-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0002_loanapplication_applicant_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='id_proof_file',
            field=models.FileField(blank=True, upload_to='nominee_id_proofs/'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='nominee_photos/'),
        ),
    ]
