# Generated by Django 5.1.7 on 2025-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0003_alter_nominee_id_proof_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loanID',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
