# Generated by Django 5.1.7 on 2025-05-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0004_alter_loanapplication_loanid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='id_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/images/nominee/idprooffile/'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/nominee/'),
        ),
    ]
