# Generated by Django 5.1.7 on 2025-05-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0005_alter_nominee_id_proof_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='manager_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('MANAGER_APPROVED', 'Manager Approved (Awaiting Admin)'), ('INFO_REQUESTED', 'Information Requested'), ('APPROVED', 'Approved (Final)'), ('ACTIVE', 'Active / Ongoing'), ('PAID', 'Paid / Closed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by Applicant'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=30),
        ),
    ]
