# Generated by Django 5.1.7 on 2025-05-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0007_emischedule_payment_processed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emischedule',
            name='emiTotalMonth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
