# Generated by Django 5.1.7 on 2025-04-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('loan_purpose', models.CharField(max_length=50)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
