# Generated by Django 5.1.7 on 2025-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outgoing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
