# Generated by Django 5.1.7 on 2025-03-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ['-date'], 'verbose_name': 'Cashflow Entry', 'verbose_name_plural': 'Cashflow Entries'},
        ),
        migrations.AddField(
            model_name='cashflow',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
