# Generated by Django 5.1.6 on 2025-03-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.CharField(editable=False, max_length=12, unique=True)),
                ('title', models.SmallIntegerField(blank=True, choices=[(1, 'Mr.'), (2, 'Mrs.'), (3, 'Ms.'), (4, 'Dr.')], default=1)),
                ('emp_type', models.SmallIntegerField(blank=True, choices=[(1, 'ADMIN'), (2, 'MANAGER'), (3, 'APPLICANT')], default=1)),
                ('empfirst_name', models.CharField(max_length=50)),
                ('empfather_name', models.CharField(max_length=50)),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], default=1)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(null=True)),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='uploads/images/employee/')),
            ],
        ),
    ]
