# Generated by Django 5.1.7 on 2025-05-09 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_system_id', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('title_choice', models.SmallIntegerField(blank=True, choices=[(1, 'Mr.'), (2, 'Mrs.'), (3, 'Ms.'), (4, 'Dr.')], null=True)),
                ('father_name', models.CharField(blank=True, max_length=50)),
                ('gender_choice', models.SmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('address_detail', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('date_of_birth_detail', models.DateField(blank=True, null=True)),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='uploads/images/employee_profiles/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_details_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Detail',
                'verbose_name_plural': 'Employee Details',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee_system_id'], name='employees_e_employe_322557_idx'), models.Index(fields=['user'], name='employees_e_user_id_23cee9_idx'), models.Index(fields=['is_deleted'], name='employees_e_is_dele_65d689_idx')],
            },
        ),
    ]
