# Generated by Django 5.1.7 on 2025-05-12 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employeedetails',
            name='employees_e_employe_322557_idx',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='employee_system_id',
            new_name='employee_id',
        ),
        migrations.AddIndex(
            model_name='employeedetails',
            index=models.Index(fields=['employee_id'], name='employees_e_employe_c5ff0c_idx'),
        ),
    ]
