# Generated by Django 5.1.7 on 2025-03-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='emp_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'ADMIN'), (2, 'MANAGER'), (3, 'APPLICANT')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='title',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Mr.'), (2, 'Mrs.'), (3, 'Ms.'), (4, 'Dr.')], default=1, null=True),
        ),
    ]
