# Generated by Django 5.1.7 on 2025-05-12 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employeedetails_employees_e_employe_322557_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='Joining Date'),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='leaving_date',
            field=models.DateField(blank=True, null=True, verbose_name='Leaving Date'),
        ),
        migrations.AddIndex(
            model_name='employeedetails',
            index=models.Index(fields=['joining_date'], name='employees_e_joining_c7ff4f_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedetails',
            index=models.Index(fields=['leaving_date'], name='employees_e_leaving_1cec24_idx'),
        ),
    ]
