# Generated by Django 5.1.7 on 2025-05-13 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeedetails_joining_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='address_detail',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='city_district',
            field=models.CharField(blank=True, max_length=100, verbose_name='City/District'),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, verbose_name='State/Province'),
        ),
        migrations.AddIndex(
            model_name='employeedetails',
            index=models.Index(fields=['country', 'state_province', 'city_district'], name='employees_e_country_829f7a_idx'),
        ),
    ]
