# Generated by Django 5.1.7 on 2025-05-06 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeedetails_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedetails',
            options={'ordering': ['-created_at'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='employeedetails',
            index=models.Index(fields=['employeeID'], name='employees_e_employe_f94858_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedetails',
            index=models.Index(fields=['email'], name='employees_e_email_6db424_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedetails',
            index=models.Index(fields=['is_deleted'], name='employees_e_is_dele_65d689_idx'),
        ),
    ]
