# Generated by Django 5.1.7 on 2025-05-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employeedetails_address_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='father_name',
        ),
    ]
