# Generated by Django 5.1.7 on 2025-05-14 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_employeedetails_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeIDProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_number', models.CharField(max_length=50)),
                ('document_file', models.FileField(upload_to='uploads/employee_id_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_proofs', to='employees.employeedetails')),
            ],
        ),
    ]
