# Generated by Django 5.1.6 on 2025-03-13 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0002_applicant_loan_count'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_term', models.IntegerField()),
                ('loan_term_type', models.IntegerField(choices=[(1, 'DAILY'), (2, 'WEEK'), (3, 'MONTH')])),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_purpose', models.IntegerField(choices=[(1, 'CHILDRENS EDUCATION'), (2, 'MEDICAL'), (3, 'BUSINESS')])),
                ('loan_purpose_other', models.TextField(blank=True, null=True)),
                ('repayment_source', models.CharField(max_length=100)),
                ('loan_id', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applicants.applicant')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_loans', to='employees.employeedetails')),
            ],
        ),
    ]
