# Generated by Django 5.1.6 on 2025-03-11 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(max_length=100)),
                ('nominee_email', models.EmailField(max_length=254)),
                ('nominee_address', models.TextField()),
                ('nominee_phone', models.CharField(max_length=15)),
                ('nominee_relationship', models.IntegerField()),
                ('nominee_id_proof_type', models.IntegerField()),
                ('nominee_id_proof_number', models.CharField(max_length=50)),
                ('nominee_id_proof_file', models.FileField(upload_to='uploads/files/nomineeproof')),
                ('nominee_photo', models.ImageField(blank=True, null=True, upload_to='uploads/images/employee/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='applicants.applicant')),
            ],
        ),
    ]
