# Generated by Django 5.1.6 on 2025-03-12 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='nominee_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='nominee_id_proof_type',
            field=models.IntegerField(choices=[(1, 'Passport'), (2, 'Aadhar Card'), (3, 'Driving License'), (4, 'Voter ID'), (5, 'Other')]),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='nominee_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='nominee_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/nominee/'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='nominee_relationship',
            field=models.IntegerField(choices=[(1, 'Parent'), (2, 'Spouse'), (3, 'Sibling'), (4, 'Child'), (5, 'Other')]),
        ),
    ]
