# Generated by Django 5.1.7 on 2025-04-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominees', '0002_alter_nominee_nominee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='nominee_id_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/files/nomineeproof'),
        ),
    ]
